### PR TITLE
Removing Volto testing profiles (was 'Bug fix testing profile multilingual')

### PR DESCRIPTION
**Pull request by ksuess**

### CODE REVIEW

**Review by jensens — APPROVED** [review]

**Comment by jensens** [comment]
Why do we need plone.volto here at all? plone.app.multilingual should be enough. The only thing Volto does is  installing volto:default and plone.app.multilingual plus configuring en/de (why? nobody knows)

so, I would prefer to not have volto in here, this package must work in both worlds, classicui and volto.

**Comment by ksuess** [comment]
The two testing profiles are setting up sites (monolingual and multilingual) ready for testing a frontend search that is relying on this packages REST service. Of course these backend testing profiles could go in a separate package, but from the perspective of a frontend package that heavily relies on a backend package, it makes sense to place these profiles here.
And to use the code of plone.volto which is nicely setting up a simple site with just the pam language folders and nothing else, plone.volto would be now one of the optional dependencies for the installation of collective.elastic.plone with option [test]. It is not meant to make plone.volto be a dependency of collective.elastic.plone, which is not needed at all. It's just for not duplicating post_install code that is already existing in plone.volto.

**Comment by ksuess** [comment]
I thought about it. And is indeed strange from the Plone Classic perspective that collective.elastic.plone[test] installs plone.volto. 
So I will remove the testing profiles here in collective.elastic.plone and create a dedicated testing package.

**Comment by ksuess** [comment]
Another topic worth thinking about, is, why not moving also the REST API service to a dedicated package. This would clean collective.elastic.plone to be a package focussed on indexing and focussed on Plone Classic with the index proxy SearchableText, freed from a service that is not for indexing but non Plone Classic searching.
What do you think?

**Comment by jensens** [comment]
@ksuess I think the rest service can live her. It depends on plone.restapi only and that is fine IMO. Also, managing many packages is not that much fun. We did this for plone.* and it creates lots of work.

**Comment by ksuess** [comment]
> @ksuess I think the rest service can live her. It depends on plone.restapi only and that is fine IMO. Also, managing many packages is not that much fun. We did this for plone.* and it creates lots of work.

That's fine for me. So I leave the REST service here.
I just remove the somehow uninvited guest, the testing profiles, to another package.

**Review by jensens — APPROVED** [review]

**Pull request merged**
